version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    network_mode: "host"
    volumes:
      - ./sql_docker/dump:/docker-entrypoint-initdb.d
      
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    network_mode: "host"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"
      }'
    volumes:
      - workingDir:/bezkoder-app/python_api
    stdin_open: true
    tty: true

  web:
    build: ./python_api
    restart: on-failure
    container_name: flask_server
    ports:
      - $FLASK_LOCAL_PORT:$FLASK_DOCKER_PORT
    network_mode: "host"
    env_file: ./.env
    volumes:
      - workingDir:/app

volumes:
  workingDir:

